/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hsbsoftwares_android_app_healthdiagnostic_nativepack_NativeMethods */

#ifndef _Included_com_hsbsoftwares_android_app_healthdiagnostic_nativepack_NativeMethods
#define _Included_com_hsbsoftwares_android_app_healthdiagnostic_nativepack_NativeMethods
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hsbsoftwares_android_app_healthdiagnostic_nativepack_NativeMethods
 * Method:    pathologyDetection
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_com_hsbsoftwares_android_app_healthdiagnostic_nativepack_NativeMethods_pathologyDetection
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
